#!/bin/bash

# Genetate license.go
find ./vendor -name 'LICENSE' | xargs tail -n +1 > temp.license && echo -e "package main \n /* Generated by script scripts/gen_license.sh */ \n const licenseText = \` `cat temp.license` \`" > license.go && rm -f temp.license
